name: Metrics
on:
  # Daily
  schedule: [{cron: "0 0 * * *"}]
  # Manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        # Auto-updates ./github-metrics.svg
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: sed-i
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Atlantic/Reykjavik
          plugin_languages: yes
